FOGL-2774 Centralised plugin packaging for RPM files
foglamp/foglamp-pkg pull request #19
Opened 2019-05-08 08:44 UTC by MarkRiddoch

Note. This must be viewed in conjunction with foglamp-south-sinusoid and foglamp-south-random to see how it works.

My aim is to package all repositories centrally for both RPM and DEB files and hence remove the duplication between plugin repositories.

2019-05-08 13:07 UTC, ashish-jabble requested changes

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +## Copyright (c) 2018 Dianomic Systems
2019

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +echo "The FogLAMP south sinusoid version is : ${version}"
`The FogLAMP ${plugin_type} ${plugin_name}  version is`

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +	git clone https://github.com/foglamp/${repos}.git
Allow branch name CLI argument (i.e $2) as an optional and its default value is `develop`
`git clone -b ${BRANCH} --single-branch https://github.com/foglamp/${repos}.git`

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +fi
unused condition

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> + cleanall - Remove all the versions, including the last one"
We should clean and cleanall from `${archive}/${arch}` directory. No such use if we clean from `/tmp` as we delete the repo at the very end of script

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +sed -i "s/Requires: foglamp/Requires: foglamp (${foglamp_version})/g" SPECS/plugin.spec
Remove this line

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/packages/RPM/SPECS/plugin.spec
> +## Copyright (c) 2018 OSIsoft, LLC
2019
OSI or Dianomic?

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/packages/RPM/SPECS/plugin.spec
> +## Copyright (c) 2018 OSIsoft, LLC
2019
OSI or Dianomic?

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/packages/RPM/SPECS/plugin.spec
> +## Copyright (c) 2018 OSIsoft, LLC
2019
OSI or Dianomic?

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +installs=plugins/${plugin_type}/${plugin_install_dirname}
```
if [ -d ${GIT_ROOT}/python ]; then
    installs=python/foglamp/plugins/${plugin_type}/${plugin_install_dirname}
else
    installs=plugins/${plugin_type}/${plugin_install_dirname}
fi
```

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +archive=`pwd`/archive
Add `archive` in .gitignore file

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +	version=`cat "${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name}" | tr -d ' ' | grep "foglamp_${plugin_type}_${plugin_name}_version" | head -1 | sed -e 's/\(.*\)=\(.*\)/\2/g'`
` foglamp_version=cat ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +	version=`cat "${GIT_ROOT}/VERSION"`
`foglamp_version=cat ${GIT_ROOT}/foglamp.version | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
`

2019-05-08 13:07 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +foglamp_version=`cat ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
Remove this line as this should be moved up on the basis of python Vs C plugin dir structure

2019-05-08 14:45 UTC, MarkRiddoch commented on plugins/make_plugin_rpm
> +fi
It is used. BRANCH is set as an environment variable to allow you to package a different branch. Although this is a kludge and something that would be better done with a command line argument.

2019-05-08 14:45 UTC, MarkRiddoch commented on plugins/make_plugin_rpm
> + cleanall - Remove all the versions, including the last one"
Yes, those options need to change really.

2019-05-09 08:26 UTC, pintomax submitted a review, later dismissed

2019-05-09 13:57 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +sed -i "s/Requires: foglamp/Requires: foglamp(${foglamp_version})/g" SPECS/plugin.spec
Remove this line and refer  https://github.com/foglamp/foglamp-pkg/pull/19/commits/d9db7f7f8c3564a223cbaf3c9b7826c472f92128#r282043778

2019-05-13 06:13 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +			sh requirements.sh
We need another exercise to update `requirements.sh` for All repos example ([opcua](https://github.com/foglamp/foglamp-south-opcua/blob/develop/requirements.sh))
`apt install` Vs `yum install`

2019-05-13 08:16 UTC, MarkRiddoch commented
As part of adding the Package and Description file to repositories we will also need to update requirements.sh to use yum install on RHEL/CentOS machines

2019-05-13 09:33 UTC, ashish-jabble commented on plugins/make_plugin_rpm
> +			find "./archive" -maxdepth 1 | grep '.*\.[0-9][0-9][0-9][0-9]' | xargs rm -rf
Remove `-maxdepth 1` as we create duplicate package with number (.0001) under root i.e `/archive`

2019-05-13 11:05 UTC, ashish-jabble approved these changes
Now approach looks good to me. We will definitely come back sometime to this again. Idea is to generate RPM packaging for plugins in a centralised way which is good.

2019-05-13 11:06 UTC, merged