FOGL-1812 - Update API's to allow installation via apt update
foglamp/foglamp-pkg pull request #9
Opened 2018-10-11 13:25 UTC by amarendra-dianomic

2018-10-25 10:31 UTC, Singhal-Vaibhav requested changes
```Linking update task
ln: failed to create symbolic link '/usr/local/foglamp/scripts/tasks/update': File exists
dpkg: error processing package foglamp (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

2018-10-25 13:59 UTC, MarkRiddoch submitted a review, later dismissed

2018-11-06 19:16 UTC, amarendra-dianomic commented
@MarkRiddoch @Singhal-Vaibhav final modifications pushed. Please check along with its companion [PR](https://github.com/foglamp/FogLAMP/pull/1177).

2018-11-14 11:44 UTC, Singhal-Vaibhav approved these changes

2018-11-14 12:39 UTC, merged